sizeX: 10
sizeY: 10
# Фактор генерации, уменьшает в n раз первичные популяции
factor_generate:  100

# задержка между рутинными операциями, ms
pause_routine: 1000

#максимальное количество циклов мира от -1 до ....
max_tick: 1000

# рендер статистики каждые n секунд. 0 - не выводить
statistics_timeout: 10

# рендерить статистику в консоль
statistics_console: true

# пауза между любыми ивентами, сек. 0 - ивенты не происходят никогда
event_timeout: 10
# шанс того, что пойдет дождь 0 - 100
сhance_rain: 30

